#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# NTFY CSRF settings
host = data.get("host", "")
base_url = "https://"+host

agent.set_env("NTFY_BASE_URL", data.get("base_url",""))
agent.set_env("NTFY_AUTH_DEFAULT_ACCESS", data.get("auth-default-access",""))
agent.set_env("NTFY_BEHIND_PROXY",data.get("behind-proxy"))
agent.set_env("NTFY_ENABLE_LOGIN", data.get("enable-login", "False"))
agent.set_env("NTFY_ENABLE_SIGNUP", data.get("enable-signup", "False"))
agent.set_env("NTFY_UPSTREAM_BASE_URE", data.get("upstream-base-url"))
agent.set_env("NTFY_UPSTREAM_ACCESS_TOKEN", data.get("upstream-access-token"))
agent.set_env("NTFY_WEB_PUSH_EMAIL_ADDRESS",data.get("web-push-email-address"))
agent.set_env("NTFY_CACHE_FILE",data.get("cache-file"))
agent.set_env("NTFY_ATTACHMENT_CACHE_DIR",data.get("attachment-cache-dir"))
agent.set_env("NTFY_AUTH_FILE",data.get("auth-file"))
agent.set_env("NTFY_WEB_PUSH_FILE",data.get("web-push-file"))
agent.set_env("NTFY_WEB_PUSH_PUBLIC_KEY",data.get("web-push-public-key"))
agent.set_env("NTFY_WEB_PUSH_PRIVATE_KEY",data.get("web-push-private-key"))


# Make sure everything is saved inside the environment file
# just before starting systemd unit
#agent.dump_env()
